//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.13.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Structure.Model.DocumentTypes
{
	// Mixin Content Type with alias "umbracoUrlAliasControls"
	/// <summary>Advanced Umbraco</summary>
	public partial interface IUmbracoUrlAliasControls : IPublishedContent
	{
		/// <summary>Redirect to Node</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent RedirectToNode { get; }

		/// <summary>Umbraco Url Alias</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		string UmbracoUrlAlias { get; }

		/// <summary>URL Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		string URlname { get; }
	}

	/// <summary>Advanced Umbraco</summary>
	[PublishedModel("umbracoUrlAliasControls")]
	public partial class UmbracoUrlAliasControls : PublishedContentModel, IUmbracoUrlAliasControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new const string ModelTypeAlias = "umbracoUrlAliasControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbracoUrlAliasControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public UmbracoUrlAliasControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Redirect to Node
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("redirectToNode")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent RedirectToNode => GetRedirectToNode(this);

		/// <summary>Static getter for Redirect to Node</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetRedirectToNode(IUmbracoUrlAliasControls that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("redirectToNode");

		///<summary>
		/// Umbraco Url Alias
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => GetUmbracoUrlAlias(this);

		/// <summary>Static getter for Umbraco Url Alias</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static string GetUmbracoUrlAlias(IUmbracoUrlAliasControls that) => that.Value<string>("umbracoUrlAlias");

		///<summary>
		/// URL Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("uRLName")]
		public virtual string URlname => GetURlname(this);

		/// <summary>Static getter for URL Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static string GetURlname(IUmbracoUrlAliasControls that) => that.Value<string>("uRLName");
	}
}
